GET http://localhost:3000/subscribers

###


GET http://localhost:3000/subscribers/6329950c6dc51df9296b38b8

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person 3",
    "subscribedToChannel": "Subscriber one"
}

###

DELETE http://localhost:3000/subscribers/6329950c6dc51df9296b38b8